- name: Setup etcd server
  become: yes
  script: "{{role_path}}/files/setup_etcd.sh"
- name: Render etcd service
  become: yes
  template:
    src: "{{role_path}}/templates/etcd.service.j2"
    dest: /etc/systemd/system/etcd.service
- name: Start etcd server
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable etcd
    systemctl start etcd
- name: Pause for 10 seconds to start things up
  pause:
    seconds: 10
