vagrant:  # vagrant specific config
  vm_box: bento/ubuntu-22.04  # OS of VMs (nodes) - do not change unless you know what you're doing
local:
  ssh_pub_key_path: ~/.ssh/id_rsa.pub  # Path to your local SSH pub key used to talk to VMs with SSH
kubernetes:
  pod_network_cidr: 10.244.0.0/24

master:
  hostname: khtw-master-0
  ip_address: 192.168.60.20
  cpu: 4
  memory: 6000

workers:
- hostname: khtw-worker-0
  ip_address: 192.168.60.30
  cpu: 1
  memory: 3000
