require 'yaml'

settings = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.box = settings['vagrant']['vm_box']

  create_vm(config, settings, settings['master'])
  settings['workers'].each do |worker|
    create_vm(config, settings, worker)
  end
end

def create_vm(config, settings, vm_settings)
  config.vm.define vm_settings["hostname"] do |machine|
    machine.vm.hostname = vm_settings["hostname"]
    machine.vm.network "private_network", ip: vm_settings["ip_address"]
    machine.vm.provider "virtualbox" do |vb|
        vb.memory  = vm_settings["memory"]
        vb.cpus    = vm_settings["cpu"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    machine.vm.provision "file", source: "#{settings['local']['ssh_pub_key_path']}", destination: "~/.ssh/id_rsa.pub"
  end
end
